version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: scraps
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./dataSQL:/var/lib
    ports:
      - "5432:5432"
